version: '3.6'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
    - client-build-temp:/app/dist 
    command: ["npm", "run", "build"]

    # links:
    #   - server
    # 前端构建完成后不会启动容器

  postgres:
    image: postgres:16
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "11223344aa"
      POSTGRES_DB: "iot-project"
    restart: always

  server:
    container_name: nestjs-backend
    build:
      context: ./server/
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - client-build-temp:/app/public # 将客户端构建的输出目录挂载到服务端的公共目录
    command: npm run start:prod
    depends_on:
      - client
      - postgres
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=11223344aa
      - DATABASE_NAME=iot-project


volumes:
  client-build-temp:
    driver: local
  postgres-data:
    driver: local